### ISSUE TITLE
VM482 WAService.js:1 Uncaught TypeError: Cannot read property 'ActiveXObject' of undefined

### ISSUE THREAD

**Issue by ihouchunyao** [lavyun/better-mock#18]
VM482 WAService.js:1 Uncaught TypeError: Cannot read property 'ActiveXObject' of undefined

**Comment by ihouchunyao** [comment]
怎么搞。？？

**Comment by lavyun** [comment]
当前还不支持小程序，正在做，下个版本会支持。

**Comment by lavyun** [comment]
https://lavyun.github.io/better-mock/document/miniprogram.html
