### ISSUE TITLE
好项目！请问该项目解决了Mockjs因覆盖XMLHttpRequest导致与三方库冲突的问题吗

### ISSUE THREAD

**Issue by uCloudCastle** [lavyun/better-mock#30]
例如该Issue：https://github.com/nuysoft/Mock/issues/364

**Comment by mengbaiai** [comment]
https://github.com/PanJiaChen/vue-element-admin
这里面封装了解决方法，可以去看看

**Comment by lavyun** [comment]
可以使用一下看看，我自己用是正常的。

**Comment by ellermister** [comment]
👍 好项目啊，解决了我的问题。头疼的 mock.js 一堆问题 折腾人好几天。

从该 issue 过来。
https://github.com/nuysoft/Mock/issues/364

简述下遇到的问题给更多人提供搜索途径。

## mock.js hook XMLRequest 没有把全部成员实现
表现：
- xx.upload.addEventListener is not a function
- 七牛等三方库上传资源时失败

解决：
装了第三方 mock.js 修复过的库
删除原有mock.js，在 package.json 增加 "mockjs": "npm:mockjs-x@^1.0.1-beta5",
编译时 遇到："error TS7016: Could not find a declaration file for module 'mockjs'."

可新建 重写文件导入，内容为：declare module 'mockjs';
具体参考 https://stackoverflow.com/a/54417184

## hls.js 无法播放视频
表现为：
- Blocking operation requested, but no SourceBuffers exist
- HLS无法播m3u8视频,编译后却可以，其中 hls 为 m3u8资源创建的buffer 于 blob文件，访问提示 ERR_FILE_NOT_FOUND

解决：
npm install better-mock
import Mock from 'better-mock';

如果想无缝替换参考第一个问题中的重写方案。
