### ISSUE TITLE
[BUG] index.d.ts 中 “image” 函数缺少返回值的类型定义

### ISSUE THREAD

**Issue by yangjunjun** [lavyun/better-mock#31]
**问题简述**
index.d.ts 中 “image” 函数缺少返回值的类型定义

https://github.com/lavyun/better-mock/blob/4362b7bb00c68e9c9225180fce67b030ba613793/typings/index.d.ts#L195

**问题截图**
![截图20200420100645464](https://user-images.githubusercontent.com/1180563/79707322-b04ec100-82ee-11ea-834f-dc22a224bd8a.jpg)

**Comment by lavyun** [comment]
已修复
