### ISSUE TITLE
使用uniapp_ts引入better-mock，控制台报Could not find a declaration file for module 'better-mock/dist/mock.mp.js'. 

### ISSUE THREAD

**Issue by songsf520** [lavyun/better-mock#36]
`Could not find a declaration file for module 'better-mock/dist/mock.mp.js'. 'C:/Codes/WorkNowCodes/miniprograme/ordermeuniapp/node_modules/better-mock/dist/mock.mp.js' implicitly has an 'any' type.
  Try `npm install @types/better-mock` if it exists or add a new declaration (.d.ts) file containing declare module 'better-mock/dist/mock.mp.js';`
怎么解决啊？

**Comment by lavyun** [comment]
已发布新版，更新版本后尝试一下
