### ISSUE TITLE
[BUG] 含 `@` 符合的 mock 数据将报错

### ISSUE THREAD

**Issue by legend80s** [lavyun/better-mock#39]
**问题简述**

含 `@` 符号的 mock 数据将报错

**复现步骤**

https://runkit.com/embed/6hqspmnzc9ih

```js
var Mock = require("better-mock")

Mock.mock({
  success: true,
  "data|3": [{
    data: {
      name: '@alipay/vc-component',
    }
  }]
})
```

报错

```
TypeError: Cannot read property '0' of undefined
```

**期望结果**
不报错

**截图**
无

**环境**
请描述一下你的代码运行环境。
 - Env: Node.js
 - better-mock version: 0.2.5

**Comment by legend80s** [comment]
mockjs 已经修复，可按照其思路修复 https://github.com/nuysoft/Mock/issues/421

**Comment by lavyun** [comment]
已修复在 v0.2.6 版本
