### ISSUE TITLE
[BUG] Mock.valid()方法——mockjs遗留的bug

### ISSUE THREAD

**Issue by inceptiongt** [lavyun/better-mock#46]
**问题简述**
valid(temp,data)方法，当temp方法里存在占位符，valid()一直返回通过

**复现步骤**
var template = {
    type: "@pick(['number','datetime','string'])"
  }
  var data = {
    type: 123
  }
  const rst = Mock.valid(template, data)
 //  rst输出 []

**期望结果**
type字段不符合

**Comment by lavyun** [comment]
已在0.2.7 解决，但是只简单校验了下类型，不会对占位符生成出来的结果做校验：

```js
Mock.valid({
  email: '@EMAIL',
}, {
  email: 123
})
// 校验不通过
```

```js
Mock.valid({
  email: '@EMAIL',
}, {
  email: '123'
})
// 校验通过
```

**Comment by inceptiongt** [comment]
> 已在0.2.7 解决，但是只简单校验了下类型，不会对占位符生成出来的结果做校验：
> 
> ```js
> Mock.valid({
>   email: '@EMAIL',
> }, {
>   email: 123
> })
> // 校验不通过
> ```
> 
> ```js
> Mock.valid({
>   email: '@EMAIL',
> }, {
>   email: '123'
> })
> // 校验通过
> ```
该项目怎么调试啊，想把这块功能完善下

**Comment by lavyun** [comment]
1. Fork `better-mock`, 然后克隆仓库到你本地。

2. 执行 `npm install` 安装依赖。

3. 当你做完功能优化后执行 `npm run build`。

4. 更新 `test/browser` 下的单测文件，保证你此次的更改都能覆盖到。

5. 提交的 commit 只用英文，格式为 `fix: your commit log (#xx)`，xx为 issue 编号。

6. 提交一个 PR 到 `better-mock`。

详细贡献指南请查看 https://github.com/lavyun/better-mock/blob/master/.github/CONTRIBUTING.md

**Comment by inceptiongt** [comment]
> 1. Fork `better-mock`, 然后克隆仓库到你本地。
> 2. 执行 `npm install` 安装依赖。
> 3. 当你做完功能优化后执行 `npm run build`。
> 4. 更新 `test/browser` 下的单测文件，保证你此次的更改都能覆盖到。
> 5. 提交的 commit 只用英文，格式为 `fix: your commit log (#xx)`，xx为 issue 编号。
> 6. 提交一个 PR 到 `better-mock`。
> 
> 详细贡献指南请查看 https://github.com/lavyun/better-mock/blob/master/.github/CONTRIBUTING.md

嗯。
还有第三部做功能的时候，怎么调试代码？
import写法不能直接运行在node里？

**Comment by lavyun** [comment]
如果想简单的调试，执行 `npm run build` 之后会在 dist 目录下生成一个 `mock.browser.js`，然后可以自己创建一个临时的 html 文件，引入这个 js 即可。例如：

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Mocha</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../node_modules/mocha/mocha.css">
  </head>
  <body>
    <script src="./dist/mock.browser.js"></script>
    <script>
      Mock.valid({
        email: '@EMAIL',
      }, {
        email: 123
      })
    </script>
  </body>
</html>
```

现在也支持 dev 模式（ https://github.com/lavyun/better-mock/commit/c0cc237dbdb7b1f67d4c4bc0e2d2063c8894e8fa ），执行 `npm run dev` 后会自动检测代码改动，生成 `mock.browser.js`
