### ISSUE TITLE
[BUG] 图片生成不支持中文标注，建议改成 https://tool.lu/imageholder/

### ISSUE THREAD

**Issue by mocobk** [lavyun/better-mock#51]
**问题简述**
使用过程中发现生成的图片不支持中文标注，如下

[https://dummyimage.com/600x400/cc00cc/470047.png&text=导入图片](https://dummyimage.com/600x400/cc00cc/470047.png&text=%E5%AF%BC%E5%85%A5%E5%9B%BE%E7%89%87)

![](https://dummyimage.com/600x400/cc00cc/470047.png&text=%E5%AF%BC%E5%85%A5%E5%9B%BE%E7%89%87)

**期望结果**
建议改成 [https://tool.lu/imageholder](https://tool.lu/imageholder/) 图片生成源， 对中文更友好，如下

[https://iph.href.lu/600x400?bg=cc00cc&fg=470047&text=导入图片](https://iph.href.lu/600x400?bg=cc00cc&fg=470047&text=导入图片)

![](https://iph.href.lu/600x400?bg=cc00cc&fg=470047&text=导入图片)

**Comment by lavyun** [comment]
已在 0.2.8 版本支持
