### ISSUE TITLE
[Feature] 希望在 dist/mock.node.js 中实现Mock.setup

### ISSUE THREAD

**Issue by limjcst** [lavyun/better-mock#58]
` dist/mock.browser.js`与` dist/mock.mp.js`中均包含`Mock.setup`方法，但`dist/mock.node.js`中没有，这给单元测试带来了麻烦。
当执行`vue-cli-service test:unit`时会提示如下错误
```
TypeError: Mock.setup is not a function
```

**Comment by lavyun** [comment]
supported in 0.2.9
