### ISSUE TITLE
[BUG] @name 和 @cname 出现的值总是一样

### ISSUE THREAD

**Issue by wll8** [lavyun/better-mock#61]
**问题简述**
@name 和 @cname 出现的值总是一样

**复现步骤**
1. 访问 mockjs 示例官网 http://mockjs.com/examples.html 并打开控制台, 粘贴以下代码:

``` js

Mock.mock({
  "data|1": [
    {
      "name": "@cname",
      "title": "@name",
    }
  ]
}).data
```
使用 better-mock@0.2.9 来运行以上代码也是一样.

**期望结果**
- @name 应该是英文的
- @cname 应该是中文的

**截图**
如果有截图，可以贴一下截图。
![image](https://user-images.githubusercontent.com/28223260/96462445-26a98d00-1258-11eb-81c4-c38a75626f52.png)

**环境**
请描述一下你的代码运行环境。
 - Env: chrome 版本 86.0.4240.75（正式版本） （64 位）
 - OS: win10x64
 - better-mock version: better-mock@0.2.9

**Comment by lavyun** [comment]
这是 mockjs 语法的一个特性：
![image](https://user-images.githubusercontent.com/22797898/96530458-15916800-12ba-11eb-9b82-1056401bf838.png)

可以使用下面的方法来解决：
```js
Mock.mock({
  "data|1": [
    {
      "name": "@CNAME",
      "title": "@NAME",
    }
  ]
}).data
```

只要保证占位符方法和变量不重名即可。

**Comment by wll8** [comment]
明白了。为了实现引用功能，所以这时候的 @name 引用的是模板键 name, 它的值是 @cname 生成的值.
