### ISSUE TITLE
[Feature] 添加类型转换规则

### ISSUE THREAD

**Issue by wll8** [lavyun/better-mock#63]
**添加生成后的数据类型转换规则**

很多时候我们知道数据的类型, 例如使用正则可以方便的创建想要的数据格式, 但目前没有找到方便的类型转换方式。

例如: `@id`, `@phone`, `/\d\d/` 类似的数据如何方便的转换为数字?

期望添加类型转换功能.

能不能在规则中去添加这个功能?
例如:

``` js
Mock.mock({data: {"age": /\d\d/}}).data.age // => "20"
// 第一个竖线表示原来的范围规则, 第二个竖线后面的字符表示类型
Mock.mock({data: {"age||number": /\d\d/}}).data.age // => 20

Mock.mock({data: {"age|3-5": /\d\d/}}).data.age // "3405820858"
Mock.mock({data: {"age|3-5|number": /\d\d/}}).data.age // 3405820858

Mock.mock({data: {"phone": `@phone`}}).data.phone // => "14927520949"
Mock.mock({data: {"phone||number": `@phone`}}).data.phone // => 14927520949
```

**Comment by lavyun** [comment]
0.3.0 版本支持了 [类型转换器](http://lavyun.gitee.io/better-mock/document/syntax-specification.html#%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2%E5%99%A8-transfer)

**Comment by wll8** [comment]
感谢. 测试了一下, 
设有如下代码: `Mock.mock({'a|3#number': '1'})` ,当前实现的效果还是认为原始值是字符串, 将生成规则与字符串处理后, 再进行类型转换.

要让原始值计算出来就是要转换的类型如何做呢?
例如: 使 `Mock.mock({'a|3#number': '1'})` 效果和 `Mock.mock({'a|3': 1})` 一致.

ps: 就我提的问题最多了, 会不会被作者讨厌?

**Comment by lavyun** [comment]
![image](https://user-images.githubusercontent.com/22797898/98346281-b4ef8280-2050-11eb-937c-6f4319541dce.png)

对于属性值来说，字符串和数字类型本来的规则就是不一样的

**Comment by wll8** [comment]
问题在于 `#number` 转换 `{'a|3': /\d\d/}` 中的 `/\d\d/` 是生成规则应用前还是后.

**Comment by lavyun** [comment]
生成后再转换

**Comment by wll8** [comment]
期待提供转换后再生成的功能.
