### ISSUE TITLE
[BUG] 扩展的方法不能与生成规则配合使用

### ISSUE THREAD

**Issue by wll8** [lavyun/better-mock#66]
**问题简述**
参考 #63 , 希望对生成的数据进行类型处理. 使用 extend 来创建一个可以转换类型的模板, 但与生成规则配合使用时, 还是会当做字符串.

**复现步骤**
``` js
window.Mock.Random.extend({
  to_number: data => {
    const res = Number(data)
    return isNaN(res) ? 0 : res
  },
})

value = Mock.mock({
  "a": "@to_number(2)"
})
console.log(`value`, value)
// out => 2

rule = Mock.mock({
  "a|1-5": "@to_number(2)"
})
console.log(`rule`, rule)
// out => "2222"

```

**期望结果**
``` js
rule = Mock.mock({
  "a|1-5": "@to_number(2)"
})
console.log(`rule`, rule)
// 输出 => "2222"
// 期望 => 4 , 即在 1-5 之间
```

**环境**
- Env: chrome 版本 86.0.4240.75（正式版本） （64 位）
- OS: win10x64
- better-mock version: better-mock@0.2.9

**Comment by lavyun** [comment]
0.3.0 版本支持了 [类型转换器](http://lavyun.gitee.io/better-mock/document/syntax-specification.html#%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2%E5%99%A8-transfer)
