### ISSUE TITLE
[BUG] 多了个debugger

### ISSUE THREAD

**Issue by zeev-kell** [lavyun/better-mock#68]
**期望结果**
这里是不是多了个 debugger 没有删除？

**截图**
![image](https://user-images.githubusercontent.com/17770012/103452002-cf1ea780-4d05-11eb-895a-a0c15aebefee.png)

**环境**
请描述一下你的代码运行环境。
 - better-mock version: v0.3.0

**Comment by lavyun** [comment]
抱歉带来困扰，已在 0.3.1 版本修复
