### ISSUE TITLE
Cannot read property 'Proxy' of undefined，小程序里没有window对象无法使用呢

### ISSUE THREAD

**Issue by dingdiudiu** [lavyun/better-mock#70]
![image](https://user-images.githubusercontent.com/6926702/104985871-de635c00-5a4c-11eb-8a3c-0c959e1e5cc4.png)

**Comment by lavyun** [comment]
小程序中需使用 `dist/mock.mp.js`，http://lavyun.gitee.io/better-mock/document/miniprogram.html
