### ISSUE TITLE
请问 新增的特性 在哪里？文档呢？ 比如Mock.Handler.gen( ) 方法 有改为  Mock.gen( ) 吗？希望能一起完善

### ISSUE THREAD

**Issue by srq18211** [lavyun/better-mock#73]
我也有fork的 想法，比如添加Mock.gen( ) 方法，丰富 imageData 的参数等

**Comment by lavyun** [comment]
新增 Mock.gen() 的原因是什么?  如果想贡献的话可以参考这份贡献指南 https://github.com/lavyun/better-mock/blob/master/.github/CONTRIBUTING.md
