### ISSUE TITLE
[BUG] @pick(text) 返回值错误

### ISSUE THREAD

**Issue by wll8** [lavyun/better-mock#75]
**问题简述**
`@pick(text)` 返回值是一个对象，而 `@pick(text1)` 返回字符串 text1 。

请求 text 有什么特殊的吗？如果特殊，如何处理？

**复现步骤**
[点此](http://lavyun.gitee.io/better-mock/) 打开控制台粘贴以下代码:
``` js
typeof Mock.mock(`@pick(text)`) // object
typeof Mock.mock(`@pick(text1)`) // string
```

**期望结果**
``` js
typeof Mock.mock(`@pick(text)`) // string
typeof Mock.mock(`@pick(text1)`) // string
```

**环境**
- Env: chrome 版本 86.0.4240.75（正式版本） （64 位）
- OS: win10x64
- better-mock version: better-mock@0.2.9

**Comment by lavyun** [comment]
不要在占位符中使用变量，应该使用基本数据，
