### ISSUE TITLE
[Feature] Add English readMe and Documents

### ISSUE THREAD

**Issue by xianshenglu** [lavyun/better-mock#76]
Hi, I really like this project and appreciate your contributions. And currently, I want to use it in my project. So, would you mind adding an English readMe and documents? Also, if possible, could we make the English readme and documents default?

I would try to provide the PR, at least for the readMe. Anyway, thanks very much for your efforts.

**Comment by lavyun** [comment]
Many features in this library are designed for Chinese people, such as `Mock.random.city`, `Mock.random.cname`,etc., so there is no translation plan for the time being.
