### ISSUE TITLE
mac上安装报错, npm装其他包都没问题

### ISSUE THREAD

**Issue by Duo-Huang** [lavyun/better-mock#77]
![image](https://user-images.githubusercontent.com/50909268/120896154-d9492700-c652-11eb-8d20-024b205f34d9.png)

**Comment by Duo-Huang** [comment]
包能装上，就是-D安装时，写入package.json时出了问题

**Comment by lavyun** [comment]
如果装不上，可以暂时下载使用 dist 中已打包后的 bundle 文件
