### ISSUE TITLE
[BUG] mock模块会影响原生的ajax请求，使得服务器返回的blob类型变成乱码

### ISSUE THREAD

**Issue by zhengxs2018** [lavyun/better-mock#78]
**问题简述**

这是 mockjs 就存在的问题，目前我们项目也遇到了。

**复现步骤**
https://www.jianshu.com/p/37ded5f2fdac
https://segmentfault.com/q/1010000014704618

**期望结果**

我们目前在代码里面添加这一行解决了

![image](https://user-images.githubusercontent.com/7506913/123217363-13447500-d4fd-11eb-92bd-3fe41ad47068.png)

参考这里的
https://segmentfault.com/q/1010000014704618

**截图**

```js
  axios.post('/api/file/xxx', data,  { responseType: 'blob' })
```

**环境**

请描述一下你的代码运行环境。

 - Env: 浏览器
 - OS: PC
 - better-mock version: 所有

**Comment by lavyun** [comment]
在 0.3.2 版本已修复
