### ISSUE TITLE
关于dataImage的处理方式

### ISSUE THREAD

**Issue by luckyyyyy** [lavyun/better-mock#83]
我看到使用了 jimp 并且因为需要同步调用，使用了promise-synchronizer

这个会有些问题，在 worker_threads 中会导致一直pending状态，建议换回原版的node-canvas

**Comment by lavyun** [comment]
node-canvas 会有一些依赖的安装问题，查看Mock issue: https://github.com/nuysoft/Mock/issues?q=node-canvas

**Comment by lavyun** [comment]
如果真的需要，可以新加一个方法，dataImageByCanvas，该方法使用 node-canvas 生成图片

**Comment by luckyyyyy** [comment]
> https://github.com/nuysoft/Mock/issues?q=node-canvas
我自己改了一个，的确node-canvas依赖非常多，大量动态库。

现在主要问题是 promise-synchronizer 在 worker_threads 中无限 pedding 似乎不可解

**Comment by lavyun** [comment]
可以参考 faker.js 实现，生成 svg 的 dataImage，https://github.com/Marak/faker.js/blob/29234378807c4141588861f69421bf20b5ac635e/lib/image.js#L214

**Comment by luckyyyyy** [comment]
thx &nbsp;我看一下&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
From: 高翔 ***@***.***&gt;
发送时间: 11/30/2021, 14:51
To: lavyun/better-mock ***@***.***&gt;
抄送: William Chan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [lavyun/better-mock] 关于dataImage的处理方式 (Issue #83)
