### ISSUE TITLE
[Proposal] 当前依赖的deasync无prebuilt支持，建议升级或者改造成peerDependencies

### ISSUE THREAD

**Issue by Matrixbirds** [lavyun/better-mock#87]
当前的版本不支持node v14 node v16的linux prebuilt。
因此要使用node-gyp，对于环境要准备python3，有点麻烦。
看了下依赖包，promise-synchronizer这个库依赖了deasync导致的

**Comment by wll8** [comment]
试试这这个呢? 

https://github.com/wll8/better-mock

**Comment by Soonze** [comment]
> 试试这这个呢?
> 
> https://github.com/wll8/better-mock
看了下，这个工程里node 端生成 base64 图片确实把要用promise-synchronizer依赖部分去除了。但是node端生成图片返回的会是promise对象了吧，不是图片了。
不过我们也用不到node端mock部分，准备自己fork一份去掉这部分。

**Comment by wll8** [comment]
做了兼容处理, node 端可以生成图片, 而不是返回 promise

**Comment by lavyun** [comment]
0.3.4 版本参考(copy)了 [faker.js](https://github.com/faker-js/faker/blob/main/src/modules/image/index.ts#L336) 的实现，并且移除了对 jimp 和 promise-synchronizer 的依赖。
